# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='casUsers',
        ),
        migrations.AddField(
            model_name='statusreport',
            name='owner',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
