# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-11 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161210_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='reactionTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reacting_user', models.CharField(max_length=100)),
                ('reaction_report', models.IntegerField()),
                ('vote', models.IntegerField(default=2)),
            ],
        ),
        migrations.AddField(
            model_name='statusreport',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statusreport',
            name='unlikes',
            field=models.IntegerField(default=0),
        ),
    ]
