# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-17 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_statusreport_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusreport',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
