# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-17 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_statusreport_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusreport',
            old_name='created',
            new_name='created_at',
        ),
    ]
