# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-18 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20161217_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusreport',
            name='pincode',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
